apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{APP_NAME}}-deployment
  labels:
    app: {{APP_NAME}}
spec:
  replicas: {{APP_REPLICAS}}
  selector:
    matchLabels:
      app: {{APP_NAME}}
      version: "{{APP_VERSION}}"
  template:
    metadata:
      labels:
        app: {{APP_NAME}}
        version: "{{APP_VERSION}}"
    spec:
      containers:
        - name: {{APP_NAME}}
          image: {{APP_REPO}}:{{APP_VERSION}}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}-service
  labels:
    app: {{APP_NAME}}
spec:
  selector:
    app: {{APP_NAME}}
    version: "{{APP_VERSION}}"
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{APP_NAME}}-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: {{APP_HOST}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{APP_NAME}}-service
                port:
                  number: 80
