# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "hbel_houS" do |hbel_houS|
    hbel_houS.vm.box = "ubuntu/focal64"
    hbel_houS.vm.network :private_network, ip: "192.168.56.110"
    hbel_houS.vm.hostname = "hbel-houS"
    hbel_houS.vm.provision "shell", inline: <<-SHELL
curl -sfL https://get.k3s.io | sh -
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
sudo install minikube-linux-amd64 /usr/local/bin/minikube
    SHELL
    hbel_houS.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
  end
end
