# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'fileutils'

FileUtils.mkdir_p("shared")
FileUtils.cp("confs/app.yaml", "shared/")

Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 600
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.synced_folder "./shared", "/vagrant"
  config.vm.define "sel-marsS" do |node|
    node.vm.hostname = "sel-marsS"
    node.vm.network "private_network", ip: "192.168.56.110"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "sel-marsS"
      vb.memory = "1024"
      vb.cpus = 1
    end
    node.vm.provision "shell", path: "scripts/sel-marsS.sh"
  end
end
