# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder "./shared", "/vagrant", create: true

  config.vm.define "sel-marsS" do |node|
    node.vm.hostname = "sel-marsS"
    node.vm.network "private_network", ip: "192.168.56.110"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "sel-marsS"
      vb.memory = "1024"
      vb.cpus = "1"
    end
    system("cp -r confs/ shared/")
    node.vm.provision "shell", path: "scripts/sel-marsS.sh"
  end
end
